"""Temporary migration message

Revision ID: 026be1271141
Revises: 
Create Date: 2023-09-20 08:48:25.825884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026be1271141'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fs_uniquifier', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_user_fs_uniquifier', ['fs_uniquifier'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('fs_uniquifier')

    # ### end Alembic commands ###
