"""added quantity in product table

Revision ID: 54f858e76a7f
Revises: 026be1271141
Create Date: 2023-09-20 09:15:11.596786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f858e76a7f'
down_revision = '026be1271141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
